### PR TITLE
Turn main into correct js

### PR DESCRIPTION
**Pull request by neojski**
Main should be a js module but it isn't.

Without this change, bundling tools interpret the file with types as js and, naturally, fail.

### CODE REVIEW

**Comment by g-plane** [comment]
Can you tell what tools will fail? Thanks.

**Comment by neojski** [comment]
It was browserify.

My setup is typescript gets converted to js via tsc compiler and then I bundle it using browserify. I also tried @vercel/ncc which, apparently, uses webpack and it was failing as well. They were both confused that main wasn't a correct js. And babel didn't translate it in the first place.

**Comment by g-plane** [comment]
This project assumes you're using transpilers. So there're three solutions:

- Consider using tools like [tsify](https://github.com/TypeStrong/tsify), or if you're using Babel, you can configure to using [@babel/preset-typescript](https://babeljs.io/docs/en/babel-preset-typescript).
- If you can't configure Babel, you can change entry of this library like this:

```diff
- import 'typed-query-selector'
+ import type {} from 'typed-query-selector'
```

- While it's not recommended, you can change your `tsconfig.json` like this without importing this library in your source code:

```json
{
  "compilerOptions": {
    "types": ["typed-query-selector"]
  }
}
```

**Comment by neojski** [comment]
I am using babel but, for some reason, it wasn't working as expected. The suggested workaround of using `import type` does work great.

Leaving the error message I got in case someone else has the same problem.

> SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing /home/neo/repos/profiler/node_modules/typed-query-selector/shim.d.ts while parsing file: /home/neo/repos/profiler/node_modules/typed-query-selector/shim.d.ts

**Pull request closed without merging**
